wirebot/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, TextAreaField, MultipleFileField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    picture = FileField('Choose Picture to Upload', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Post')

#### Find fix for MultipleFileField #####
class PictureForm(FlaskForm):
    picture_list = MultipleFileField('Select All Pictures to Upload', validators=[FileAllowed(['jpg', 'png']), DataRequired()])
    submit = SubmitField('Upload')

wirebot/posts/routes.py
from datetime import datetime, date
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from sqlalchemy import select
from wirebot import db
from wirebot.models import Post, Photo, Location
from wirebot.posts.forms import PostForm, PictureForm
from wirebot.posts.utils import save_picture_post, save_picture_plant, save_picture_ftp


posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        if form.picture.data:
            save_picture_post(form.picture.data, post)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',form=form, legend='New Post')


# url for specific posts
@posts.route("/post/<int:post_id>")   # expecitng post id to be integer
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Post updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',form=form, legend='Update post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post deleted!', 'danger')
    return redirect(url_for('main.home'))

@posts.route("/pictures", methods=['GET', 'POST'])
@login_required
def pictures():
    form = PictureForm()
    if form.validate_on_submit():
        if form.picture_list.data:
            new_photos = save_picture_plant(form.picture_list.data) # Getting back list of Photo class objects
        for pic in new_photos:
            db.session.add(pic)
            db.session.commit()
        flash('Your pictures have been added!', 'success')
        return redirect(url_for('posts.pictures'))

    new_ftp_photos = save_picture_ftp()
    for pic in new_ftp_photos:
        db.session.add(pic)
        db.session.commit()
    
    # dates = list(Photo.query.order_by(Photo.date_uploaded.desc()).with_entities(Photo.date_uploaded).all())
    # new_dates = []
    # for picture_date in dates:

    #     y_m_d = picture_date.date()
    #     if y_m_d in new_dates:
    #         pass
    #     else:
    #         new_dates += y_m_d

    # print(new_dates)

    page = request.args.get('page', 1, type=int)
    photos = Photo.query.order_by(Photo.date_uploaded.desc()).paginate(page=page, per_page=12)
    return render_template('pictures.html', title='Pictures', form=form, photos=photos, legend='Pictures')

wirebot/users/routes.py
from datetime import datetime, time, timedelta
from flask import render_template, url_for, flash, redirect, request, Blueprint, current_app
from flask_login import login_user, current_user, logout_user, login_required
from wirebot import db, bcrypt
from wirebot.models import User, Post, Status, RunTime
from wirebot.utils import run_wirebot, stop_wirebot
from wirebot.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from wirebot.users.utils import save_picture_user, send_reset_email, update_dashboard
import random, threading, calendar


users = Blueprint('users', __name__, template_folder='templates')

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:   
        return redirect(url_for('main.home'))    # if already logged in, register page sends to homepage
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to login!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))    # if already logged in, login page sends to homepage
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):  # check saved password vs. entered password
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash('Login successful.', 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))  # go to next page if one exists (account page before logging in)
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()                               # knows current_user is logged in
    return redirect(url_for('main.home'))       # sends to homepage after logout

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    # Updating account information via form on POST request
    if form.validate_on_submit():
        # Updating profile picture using save_picture()
        if form.picture.data:
            picture_file = save_picture_user(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account updated!', 'success')
        return redirect(url_for('users.account'))
    # Displaying current account information within form on GET request
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)  # pulling profile picture from static directory, within profile_pic folder getting current User image_file
    return render_template('account.html', title='Acount', image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


# Requesting token
@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with password reset instructions.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


# Once user has token from email
@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


# Checking status -> update_dashboard -> dashboard_values -> dashboard
@users.app_context_processor    # Using app_context_processor to inject values available even outside blueprint
def inject_load():
    connection = Status.query.filter_by(id=1).first().connection
    connection = 'Yes' if connection == True else 'No'

    row_num = Status.query.filter_by(id=1).first().row_num + 1

    status = ''
    if Status.query.filter_by(id=1).first().capturing == True:
        status = 'Capturing'
    elif Status.query.filter_by(id=1).first().rotating == True:
        status = 'Rotating'
    elif Status.query.filter_by(id=1).first().shifting == True:
        status = 'Shifting'
    elif Status.query.filter_by(id=1).first().finishing == True:
        status = 'Finishing'

    current_run_time = time()
    previous_run_time = RunTime.query.order_by(RunTime.id.desc()).first().run_time
    # Check if bot is finishing (returning home)
    if Status.query.filter_by(id=1).first().finishing:
        # Check if home operation has completed. If yes, then display total run time
        if RunTime.query.order_by(RunTime.id.desc()).first().run_time == None:
            current_run_time = datetime.now() - RunTime.query.order_by(RunTime.id.desc()).first().start_time
            total_seconds = int(current_run_time.total_seconds())
            hours, remainder = divmod(total_seconds,60*60)
            minutes, seconds = divmod(remainder,60)
            current_run_time = time(hours, minutes, seconds)    # Getting current run time while operating
            previous_run_time = 'Wirebot still running'
    elif Status.query.filter_by(id=1).first().connection:
        current_run_time = datetime.now() - RunTime.query.order_by(RunTime.id.desc()).first().start_time
        total_seconds = int(current_run_time.total_seconds())
        hours, remainder = divmod(total_seconds,60*60)
        minutes, seconds = divmod(remainder,60)
        current_run_time = time(hours, minutes, seconds)    # Getting current run time while operating
    
    return {'connection': connection, 'status': status, 'row_num': row_num, 'current_run_time': current_run_time, 'previous_run_time': previous_run_time}


@users.before_app_first_request
def before_request():
    # Starts background thread for function we need to run before first client connects
    threading.Thread(target=update_dashboard, args=(current_app._get_current_object(), )).start()

# Dashboard route including html buttons that save to status file -> send websocket update
@users.route("/dashboard", methods=['GET', 'POST'])
@login_required
def dashboard():
    if request.method == 'POST':
        if request.form.get('run') == 'run':
            run_wirebot()
        elif request.form.get('stop') == 'stop':
            stop_wirebot()

    elif request.method == 'GET':
        return render_template('dashboard.html')


    return render_template('dashboard.html', title='Dashboard')


# @users.app_context_processor    # Using app_context_processor to inject values available even outside blueprint
# def inject_status():
#     load = [int(random.random() * 100) / 10 for _ in range(3)]
#     return {'load1': load[0], 'load5': load[1], 'load15': load[2]}

@users.route("/Wirebot_Status", methods=['GET'])
@login_required
def wirebot_status():
    
    return render_template('wirebot_status.html', title='Wirebot Status')


# Calendar display *** Incorporate time preset on specific days
@users.route("/Calendar", methods=['GET', 'POST'])
@login_required
def calendar_page():
    currentMonth = datetime.now().month
    currentYear = datetime.now().year
    calendar_current_month = calendar.month(currentYear, currentMonth)
    return render_template('calendar_page.html', title='Calendar', calendar_current_month=calendar_current_month)

@users.route("/Alerts", methods=['GET'])
@login_required
def alerts():

    return render_template('alerts.html', title='Alerts')

wirebot/templates/about.html
{% extends "layout.html" %}
{% block content %}
<legend class="border-bottom mb-4" style="font-size:40px">What is a Wirebot?</legend>
    <body>
        <h4 style="padding-inline: 5px; padding-bottom: 10px">A wirebot is a a motor driven device that travels along a cable or cord.</h4>
        <h5 style="padding-inline: 5px; padding-bottom: 10px">This web application allows users to control their wirebot and view pictures it has taken.</h5>
    </body>
{% endblock content %}

wirebot/templates/alerts.html
{% extends "layout.html" %}
<body>
    {% block content %}
    <div class="content-section">
        <div class="media">
        <img class="rounded-circle account-img" src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Alerts</legend>
        <div class="form-group">
            <p class="article-content">### Alerts Under Construction ###</p>
        </div>
    {% endblock content %}
</body>

wirebot/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <!--Upload picture with post-->
            <div class="form-group">
                {{ form.picture.label() }}
                {{ form.picture(class="form-control-file") }}
                {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                        <span class="text-danger">{{ error }}</span></br>
                    {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

wirebot/templates/dashboard.html
{% extends "layout.html" %}
<body>
    {% block content %}
    <div class="content-section">
        <div class="media">
        <img class="rounded-circle account-img" src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <legend class="border-bottom mb-4" style="font-size:40px">Dashboard</legend>
    <div class="body">
        <p class="h5" font-weight="bold">Wirebot Controls</p>
        <div class="form-group">
            <form method="post" action="/dashboard">
                <button class="b b-run" type="submit" name="run" value="run">Run</button>
                <button class="b b-stop" type="submit" name="stop" value="stop">Stop</button>
            </form>
        </div>
        <p class="h5" font-weight="bold">Wirebot Status</p>
        {% include "dashboard_values.html" %}
    </div>
    {% endblock content %}
</body>

wirebot/templates/dashboard_values.html
<div id="dashboard_values" class="load">
    <table>
      <tr><th>Connected</th><th>Operation</th><th>Current Row</th><th>Current Run Time</th><th>Previous Run Time</th></tr>
      <tr><td>{{ connection }}</td><td>{{ status }}</td><td>{{ row_num }}</td><td>{{ current_run_time }}</td><td>{{ previous_run_time }}</td></tr>
    </table>
  </div>

wirebot/templates/home.html
{% extends "layout.html" %}
{% block content %}
<legend class="border-bottom mb-4" style="font-size:40px; padding-left: 3rem;">Home of the Greenhouse Wirebot</legend>
<div class="body" style="text-align: center;">
  <p class="h5" font-weight="bold" style="text-align: center;">Designed for greenhouses and high tunnels</p>
  <img width="50%" src="{{ url_for('static', filename='home_pics/' + greenhouse) }}">
  <p class="h5" font-weight="bold"> </p>
  <img width="50%" src="{{ url_for('static', filename='home_pics/' + integrated_system) }}">
</div>
{% endblock content %}

wirebot/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Greenhouse Wirebot - {{ title }}</title>
    {% else %}
        <title>Greenhouse Wirebot</title>
    {% endif %}
    
    {{ turbo() }}<!-- Initialize turbo.js library -->
  </head>


<body>
    <header class="site-header">
      <!-- Top Ribbon Bar -->
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Greenhouse Wirebot</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>

      <!-- Sidebar -->
      <nav id="sidebarMenu" class="collpase d-lg-block sidebar bg-white">
        <div class="position-sticky">
          <div class="list-group list-group-flush mx-3 mt-4">
            <a href="{{ url_for('users.dashboard') }}" class="list-group-item list-group-item-action py-2 ripple" aria-current="true">
              <i class="fas fa-tachometer-alt fa-fw me-3"></i><span>Dashboard</span>
            </a>
            <a href="{{ url_for('posts.pictures') }}" class="list-group-item list-group-item-action py-2 ripple">
              <i class="fas fa-chart-area fa-fw me-3"></i><span>Pictures</span>
            </a>
            <a href="{{ url_for('main.run_times') }}" class="list-group-item list-group-item-action py-2 ripple">
              <i class="fas fa-lock fa-fw me-3"></i><span>Run Times</span>
            </a>
            <a href="{{ url_for('users.calendar_page') }}" class="list-group-item list-group-item-action py-2 ripple">
              <i class="fas fa-calendar fa-fw me-3"></i><span>Calendar</span>
              </a>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

wirebot/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

wirebot/templates/post.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            {% if post.author == current_user %}
                <div>
                    <a class ="btn btn-primary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
                </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>
        {% if post.picture %}
        <body>
          <img src="{{ url_for('static', filename='post_pics/' + post.picture) }}">
        </body>
        {% endif %}
        </div>
    </article>
<!-- Modal (Popup for Confirmation)-->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <!-- Button referencing to delete post form -->
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete"> 
          </form>  
        </div>
      </div>
    </div>
</div>
{% endblock content %}

wirebot/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Rest Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

wirebot/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
            {% if post.picture %}
            <body>
              <img src="{{ url_for('static', filename='post_pics/' + post.picture) }}">
            </body>
            {% endif %}
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

wirebot/templates/wirebot_status.html
{% extends "layout.html" %}
<body>
    {% block content %}
    <div class="content-section">
        <div class="media">
        <img class="rounded-circle account-img" src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Wirebot Status</legend>
        <div class="form-group">
            <p class="article-content">### Status Under Construction ###</p>
        </div>
    {% endblock content %}
</body>